# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => "Chicago" }, { :name => "Copenhagen" }])
#   Mayor.create(:name => "Emanuel", :city => cities.first)

Line.create([{:id => 1, :name => "A"}, {:id => 2, :name => "B"}, {:id => 3, :name => "C"}, {:id => 4, :name => "D"}, {:id => 5, :name => "E"}]) 

Location.create [
                  {:id => 1, :name => "110 Broad Street"},
                  {:id => 2, :name => "Academic Dr."},
                  {:id => 3, :name => "Bookstore"},
                  {:id => 4, :name => "Case-Geyer Library"},
                  {:id => 5, :name => "Cutten Hall"},
                  {:id => 6, :name => "Frank Dining Hall"},
                  {:id => 7, :name => "Gate House"},
                  {:id => 8, :name => "Kendrick & Broad"},
                  {:id => 9, :name => "Maple & Lebanon"},
                  {:id => 10, :name => "Newell Apartments"},
                  {:id => 11, :name => "Parker Apartments"},
                  {:id => 12, :name => "Parry's Plaza"},
                  {:id => 13, :name => "Perrson Hall"},
                  {:id => 14, :name => "Price Chopper"},
                  {:id => 15, :name => "SOMAC"},
                  {:id => 16, :name => "Townhouses"},
                  {:id => 17, :name => "University Ct./Burch"},
                  {:id => 18, :name => "Village Green"},
                  {:id => 19, :name => "Whitnall Field"},
                ]
                  

Stop.create [
               {:line_id => 1, :location_id => 1, :time => "07:51", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 1, :time => "08:51", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 1, :time => "09:51", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 1, :time => "10:51", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 1, :time => "11:51", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 1, :time => "12:51", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 1, :time => "13:51", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 1, :time => "14:51", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 1, :time => "15:53", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 1, :time => "16:53", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 1, :time => "18:21", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 1, :time => "19:21", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 1, :time => "20:21", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 1, :time => "21:21", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 1, :time => "22:21", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 1, :time => "23:21", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 1, :time => "00:21", :days => "Thursday,Friday,Saturday"},
               {:line_id => 1, :location_id => 1, :time => "01:21", :days => "Thursday,Friday,Saturday"},
               {:line_id => 1, :location_id => 1, :time => "02:21", :days => "Thursday,Friday,Saturday"},

               {:line_id => 1, :location_id => 2, :time => "08:09", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 2, :time => "08:09", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 2, :time => "09:09", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 2, :time => "10:09", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 2, :time => "11:09", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 2, :time => "01:09", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 2, :time => "02:09", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 2, :time => "03:09", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 2, :time => "04:11", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 2, :time => "05:11", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 2, :time => "06:39", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 2, :time => "07:39", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 2, :time => "08:39", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 2, :time => "09:39", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 2, :time => "10:39", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 2, :time => "11:39", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 2, :time => "12:39", :days => "Thursday,Friday,Saturday"},
               {:line_id => 1, :location_id => 2, :time => "13:39", :days => "Thursday,Friday,Saturday"},
               {:line_id => 1, :location_id => 2, :time => "14:39", :days => "Thursday,Friday,Saturday"},

               {:line_id => 1, :location_id => 4, :time => "08:06", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 4, :time => "08:06", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 4, :time => "09:06", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 4, :time => "10:06", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 4, :time => "11:06", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 4, :time => "01:06", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 4, :time => "02:06", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 4, :time => "03:06", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 4, :time => "04:08", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 4, :time => "05:08", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 4, :time => "06:36", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 4, :time => "07:36", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 4, :time => "08:36", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 4, :time => "09:36", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 4, :time => "10:36", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 4, :time => "11:36", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 4, :time => "12:36", :days => "Thursday,Friday,Saturday"},
               {:line_id => 1, :location_id => 4, :time => "13:36", :days => "Thursday,Friday,Saturday"},
               {:line_id => 1, :location_id => 4, :time => "14:36", :days => "Thursday,Friday,Saturday"},

               {:line_id => 1, :location_id => 5, :time => "07:54", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 5, :time => "08:54", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 5, :time => "09:54", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 5, :time => "10:54", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 5, :time => "11:54", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 5, :time => "12:54", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 5, :time => "13:54", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 5, :time => "14:54", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 5, :time => "15:56", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 5, :time => "16:56", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 5, :time => "18:24", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 5, :time => "19:24", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 5, :time => "20:24", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 5, :time => "21:24", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 5, :time => "22:24", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 5, :time => "23:24", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 5, :time => "00:24", :days => "Thursday,Friday,Saturday"},
               {:line_id => 1, :location_id => 5, :time => "01:24", :days => "Thursday,Friday,Saturday"},
               {:line_id => 1, :location_id => 5, :time => "02:24", :days => "Thursday,Friday,Saturday"},

               {:line_id => 1, :location_id => 6, :time => "08:18", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 6, :time => "08:18", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 6, :time => "09:18", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 6, :time => "10:18", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 6, :time => "11:18", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 6, :time => "01:18", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 6, :time => "02:18", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 6, :time => "03:18", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 6, :time => "04:20", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 6, :time => "05:20", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 6, :time => "06:48", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 6, :time => "07:48", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 6, :time => "08:48", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 6, :time => "09:48", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 6, :time => "10:48", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 6, :time => "11:48", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 6, :time => "12:48", :days => "Thursday,Friday,Saturday"},
               {:line_id => 1, :location_id => 6, :time => "13:48", :days => "Thursday,Friday,Saturday"},
               {:line_id => 1, :location_id => 6, :time => "14:48", :days => "Thursday,Friday,Saturday"},

               {:line_id => 1, :location_id => 7, :time => "08:12", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 7, :time => "08:12", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 7, :time => "09:12", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 7, :time => "10:12", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 7, :time => "11:12", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 7, :time => "01:12", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 7, :time => "02:12", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 7, :time => "03:12", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 7, :time => "04:14", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 7, :time => "05:14", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 7, :time => "06:42", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 7, :time => "07:42", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 7, :time => "08:42", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 7, :time => "09:42", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 7, :time => "10:42", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 7, :time => "11:42", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 7, :time => "12:42", :days => "Thursday,Friday,Saturday"},
               {:line_id => 1, :location_id => 7, :time => "13:42", :days => "Thursday,Friday,Saturday"},
               {:line_id => 1, :location_id => 7, :time => "14:42", :days => "Thursday,Friday,Saturday"},

               {:line_id => 1, :location_id => 8, :time => "08:25", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 8, :time => "08:25", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 8, :time => "09:25", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 8, :time => "10:25", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 8, :time => "11:25", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 8, :time => "01:25", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 8, :time => "02:25", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 8, :time => "03:25", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 8, :time => "04:27", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 8, :time => "05:27", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 8, :time => "06:55", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 8, :time => "07:55", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 8, :time => "08:55", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 8, :time => "09:55", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 8, :time => "10:55", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 8, :time => "11:55", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 8, :time => "12:55", :days => "Thursday,Friday,Saturday"},
               {:line_id => 1, :location_id => 8, :time => "13:55", :days => "Thursday,Friday,Saturday"},
               {:line_id => 1, :location_id => 8, :time => "14:55", :days => "Thursday,Friday,Saturday"},                           

               {:line_id => 1, :location_id => 9, :time => "07:36", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 9, :time => "08:36", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 9, :time => "09:36", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 9, :time => "10:36", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 9, :time => "11:36", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 9, :time => "12:36", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 9, :time => "13:36", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 9, :time => "14:38", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 9, :time => "15:38", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 9, :time => "16:36", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 9, :time => "18:06", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 9, :time => "19:06", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 9, :time => "20:06", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 9, :time => "21:06", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 9, :time => "22:06", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 9, :time => "23:06", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 9, :time => "00:06", :days => "Thursday,Friday,Saturday"},
               {:line_id => 1, :location_id => 9, :time => "01:06", :days => "Thursday,Friday,Saturday"},
               {:line_id => 1, :location_id => 9, :time => "02:06", :days => "Thursday,Friday,Saturday"},

               {:line_id => 1, :location_id => 10, :time => "07:42", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 10, :time => "08:42", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 10, :time => "09:42", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 10, :time => "10:42", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 10, :time => "11:42", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 10, :time => "12:42", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 10, :time => "13:42", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 10, :time => "14:44", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 10, :time => "15:44", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 10, :time => "16:42", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 10, :time => "18:12", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 10, :time => "19:12", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 10, :time => "20:12", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 10, :time => "21:12", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 10, :time => "22:12", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 10, :time => "23:12", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 10, :time => "00:12", :days => "Thursday,Friday,Saturday"},
               {:line_id => 1, :location_id => 10, :time => "01:12", :days => "Thursday,Friday,Saturday"},
               {:line_id => 1, :location_id => 10, :time => "02:12", :days => "Thursday,Friday,Saturday"},

               {:line_id => 1, :location_id => 11, :time => "07:48", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 11, :time => "08:48", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 11, :time => "09:48", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 11, :time => "10:48", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 11, :time => "11:48", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 11, :time => "12:48", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 11, :time => "13:48", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 11, :time => "14:50", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 11, :time => "15:50", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 11, :time => "16:48", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 11, :time => "18:18", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 11, :time => "19:18", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 11, :time => "20:18", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 11, :time => "21:18", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 11, :time => "22:18", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 11, :time => "23:18", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 11, :time => "00:18", :days => "Thursday,Friday,Saturday"},
               {:line_id => 1, :location_id => 11, :time => "01:18", :days => "Thursday,Friday,Saturday"},
               {:line_id => 1, :location_id => 11, :time => "02:18", :days => "Thursday,Friday,Saturday"},

               {:line_id => 1, :location_id => 12, :time => "15:35", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 12, :time => "16:35", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 12, :time => "18:05", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 12, :time => "19:05", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},

               {:line_id => 1, :location_id => 13, :time => "08:15", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 13, :time => "08:15", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 13, :time => "09:15", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 13, :time => "10:15", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 13, :time => "11:15", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 13, :time => "01:15", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 13, :time => "02:15", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 13, :time => "03:15", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 13, :time => "04:17", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 13, :time => "05:17", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 13, :time => "06:45", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 13, :time => "07:45", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 13, :time => "08:45", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 13, :time => "09:45", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 13, :time => "10:45", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 13, :time => "11:45", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 13, :time => "12:45", :days => "Thursday,Friday,Saturday"},
               {:line_id => 1, :location_id => 13, :time => "13:45", :days => "Thursday,Friday,Saturday"},
               {:line_id => 1, :location_id => 13, :time => "14:45", :days => "Thursday,Friday,Saturday"},
               {:line_id => 1, :location_id => 13, :time => "08:21", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 13, :time => "08:21", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 13, :time => "09:21", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 13, :time => "10:21", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 13, :time => "11:21", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 13, :time => "01:21", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 13, :time => "02:21", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 13, :time => "03:21", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 13, :time => "04:23", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 13, :time => "05:23", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 13, :time => "06:51", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 13, :time => "07:51", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 13, :time => "08:51", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 13, :time => "09:51", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 13, :time => "10:51", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 13, :time => "11:51", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 13, :time => "12:51", :days => "Thursday,Friday,Saturday"},
               {:line_id => 1, :location_id => 13, :time => "13:51", :days => "Thursday,Friday,Saturday"},
               {:line_id => 1, :location_id => 13, :time => "14:51", :days => "Thursday,Friday,Saturday"},             

               {:line_id => 1, :location_id => 14, :time => "15:33", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 14, :time => "16:33", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 14, :time => "18:03", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 14, :time => "19:03", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 14, :time => "20:03", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},

               {:line_id => 1, :location_id => 15, :time => "07:39", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 15, :time => "08:39", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 15, :time => "09:39", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 15, :time => "10:39", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 15, :time => "11:39", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 15, :time => "12:39", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 15, :time => "13:39", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 15, :time => "14:41", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 15, :time => "15:41", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 15, :time => "16:39", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 15, :time => "18:09", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 15, :time => "19:09", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 15, :time => "20:09", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 15, :time => "21:09", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 15, :time => "22:09", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 15, :time => "23:09", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 15, :time => "00:09", :days => "Thursday,Friday,Saturday"},
               {:line_id => 1, :location_id => 15, :time => "01:09", :days => "Thursday,Friday,Saturday"},
               {:line_id => 1, :location_id => 15, :time => "02:09", :days => "Thursday,Friday,Saturday"},

               {:line_id => 1, :location_id => 16, :time => "07:58", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 16, :time => "08:58", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 16, :time => "09:58", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 16, :time => "10:58", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 16, :time => "11:58", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 16, :time => "12:58", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 16, :time => "13:58", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 16, :time => "14:58", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 16, :time => "15:60", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 16, :time => "16:60", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 16, :time => "18:28", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 16, :time => "15:60", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 16, :time => "16:60", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 16, :time => "15:60", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 16, :time => "16:60", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 16, :time => "19:28", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 16, :time => "20:28", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 16, :time => "21:28", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 16, :time => "22:28", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 16, :time => "23:28", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 16, :time => "00:28", :days => "Thursday,Friday,Saturday"},
               {:line_id => 1, :location_id => 16, :time => "01:28", :days => "Thursday,Friday,Saturday"},
               {:line_id => 1, :location_id => 16, :time => "02:28", :days => "Thursday,Friday,Saturday"},

               {:line_id => 1, :location_id => 17, :time => "07:45", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 17, :time => "08:45", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 17, :time => "09:45", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 17, :time => "10:45", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 17, :time => "11:45", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 17, :time => "12:45", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 17, :time => "13:45", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 17, :time => "14:47", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 17, :time => "15:47", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 17, :time => "16:45", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 17, :time => "18:15", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 17, :time => "19:15", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 17, :time => "20:15", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 17, :time => "21:15", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 17, :time => "22:15", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 17, :time => "23:15", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 17, :time => "00:15", :days => "Thursday,Friday,Saturday"},
               {:line_id => 1, :location_id => 17, :time => "01:15", :days => "Thursday,Friday,Saturday"},
               {:line_id => 1, :location_id => 17, :time => "02:15", :days => "Thursday,Friday,Saturday"},

               {:line_id => 1, :location_id => 18, :time => "07:30", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 18, :time => "08:30", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 18, :time => "09:30", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 18, :time => "10:30", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 18, :time => "11:30", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 18, :time => "12:30", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 18, :time => "13:30", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 18, :time => "14:30", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 18, :time => "15:30", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 18, :time => "16:30", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 18, :time => "18:00", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 18, :time => "19:00", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 18, :time => "20:00", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 18, :time => "21:00", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 18, :time => "22:00", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 18, :time => "23:00", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 18, :time => "00:00", :days => "Thursday,Friday,Saturday"},
               {:line_id => 1, :location_id => 18, :time => "01:00", :days => "Thursday,Friday,Saturday"},
               {:line_id => 1, :location_id => 18, :time => "02:00", :days => "Thursday,Friday,Saturday"},

               {:line_id => 1, :location_id => 19, :time => "08:03", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 19, :time => "09:03", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 19, :time => "10:03", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 19, :time => "11:03", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 19, :time => "01:03", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 19, :time => "02:03", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 19, :time => "03:03", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 19, :time => "04:05", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 19, :time => "05:05", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 19, :time => "06:33", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 19, :time => "07:33", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 19, :time => "08:33", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 19, :time => "09:33", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 19, :time => "10:33", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 19, :time => "11:33", :days => "Monday,Tuesday,Wednesday,Thursday,Friday"},
               {:line_id => 1, :location_id => 19, :time => "12:33", :days => "Thursday,Friday,Saturday"},
               {:line_id => 1, :location_id => 19, :time => "13:33", :days => "Thursday,Friday,Saturday"},
               {:line_id => 1, :location_id => 19, :time => "14:33", :days => "Thursday,Friday,Saturday"}
            ]
